### ISSUE TITLE
chore: use cimg/postgres

### ISSUE THREAD

**Issue by cexbrayat** [Ninja-Squad/rare-basket#25]
Our CI build uses `circleci/postgres:11.1-alpine-ram`

This is a deprecated image, but we can't use cimg/postgres as it does not have the FR locale https://github.com/CircleCI-Public/cimg-postgres/issues/17

**Comment by hwsoderlund** [comment]
Just FYI, for now I have solved my problem using `postgres:9-alpine` which does have the swedish locale pre-installed. So you could try `postgres:11-alpine` and see if it works for FR.

**Comment by hwsoderlund** [comment]
Btw, I am now referring to the official postgres images, not the circle convenience images. 

https://hub.docker.com/_/postgres

**Comment by cexbrayat** [comment]
@hwsoderlund Thanks for letting us know! I'll give that a try 👍

**Comment by cexbrayat** [comment]
Thanks @hwsoderlund : the official postgres image does the job
